name: CI
on:
  push:
    branches:
      - main
      - kunal-final-tweaks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Run WASM Build
        run: make wasm
